### ISSUE TITLE
2019/04/08 - 微信小程序云数据库的复杂操作

### ISSUE THREAD

**Issue by godpowerscn** [BooheeFE/weekly#34]
## 广而告之

本文发布于[zhanlanxinxi]，欢迎Watch & Star ★，转载请注明出处。
### 欢迎讨论，点个赞再走吧  ｡◕‿◕｡ ～

//使用where筛选结果进行删除操作
const cloud = require('wx-server-sdk')
cloud.init()
const db = cloud.database()
exports.main = async (event, context) => {
  try {
    return await db.collection('todos').where({
      done: true
    }).remove()
  } catch(e) {
    console.error(e)
  }
}

**Comment by simbawus** [comment]
这是技术文章分享平台，请勿随意开issue，谢谢配合。

**Comment by godpowerscn** [comment]
不好意思，我不太熟悉这个。我也奇怪怎么跑这里来了，对不起
